# Generated by Django 2.2.6 on 2020-02-10 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('walletapp', '0007_auto_20200210_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_library_identifier', models.CharField(max_length=50, unique=True, verbose_name='Device identifier')),
                ('push_token', models.CharField(max_length=250, verbose_name='Push token')),
            ],
            options={
                'verbose_name': 'Connected device',
                'verbose_name_plural': 'Connected devices',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.Device', verbose_name='Associated device')),
                ('pass_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walletapp.Pass', verbose_name='Apple Wallet pass')),
            ],
            options={
                'verbose_name': 'Relation: pass - device',
                'verbose_name_plural': 'Relations: pass - device',
                'ordering': ['-pk'],
                'unique_together': {('pass_object', 'device')},
            },
        ),
    ]
